title: LMSX
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

nav_external_links:
  - title: Memoria VRAM
    url: https://es.wikipedia.org/wiki/Memoria_gr%C3%A1fica_de_acceso_aleatorio
    opens_in_new_tab: true

color_scheme: dark

logo: "/jsangs.github.io/descarga.jpg"
